---
Title: Running MultiQC on a subset of the sample sequences
Author: Chris M
Date: October 30, 2025
---

# All Sequences

| Sequence ID (all have 2 reads) | Site Name | PAH Group |
|----|----|----|
| 69 | Elliot Bay, Myrtle Edwards | 6 |
| 70 | Elliot Bay, Myrtle Edwards | 6 |
| 71 | Elliot Bay, Myrtle Edwards | 6 |
| 72 | Elliot Bay, Myrtle Edwards | 6 |
| 78 | Seattle Aquarium, Pier 59 | 5 |
| 79 | Seattle Aquarium, Pier 59 | 5 |
| 80 | Seattle Aquarium, Pier 59 | 5 |
| 81 | Seattle Aquarium, Pier 59 | 5 |
| 92 | Smith Cove, Terminal 91 | 4 |
| 93 | Smith Cove, Terminal 91 | 4 |
| 94 | Smith Cove, Terminal 91 | 4 |
| 95 | Smith Cove, Terminal 91 | 4 |
| 105 | Hood Canal Holly | 2 |
| 106 | Hood Canal Holly | 2 |
| 107 | Hood Canal Holly | 2 |
| 109 | Hood Canal Holly | 2 |
| 239 | Aiston Preserve | 1 |
| 240 | Aiston Preserve | 1 |
| 241 | Aiston Preserve | 1 |
| 242 | Aiston Preserve | 1 |
| 269 | Broad Spit, Fisherman's Point | 3 |
| 270 | Broad Spit, Fisherman's Point | 3 |
| 271 | Broad Spit, Fisherman's Point | 3 |
| 272 | Broad Spit, Fisherman's Point | 3 |
| *Note:* Lowest=1, Highest=6 | Low Sites= 1-3 | High Sites= 4-6 |

: All sequences by PAH grouping

## Selected Sequences for Test Run post QC: Samples 69 and 239 (both reads for each)

### All files for the process are manipulated from the code in [Steven's Project Mytilus Repo](https://github.com/RobertsLab/project-mytilus-methylation/tree/main)
