name: bio-cli
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pip
  # Core IO & system
  - curl
  - aria2
  - wget
  - pigz
  - parallel
  - grep
  - sed
  - coreutils
  # QC
  - fastqc
  - multiqc
  - fastp
  # Alignment stacks
  - bowtie2
  - hisat2
  - samtools
  - bedtools
  - bwa                      # handy to have
  # Bisulfite
  - bismark
  - perl
  - perl-threaded
  # Utilities for tabix/bgzip (useful with methylKit & others)
  - htslib
  - bcftools
  # Reference helpers
  - seqkit
  - ucsc-bedgraphtobigwig    # sometimes useful
  # R helpers for command-line Bioc installs later
  - r-base=4.3
  - r-essentials
  - r-devtools
  # Optional R pkgs via conda (you can also install in RStudio instead)
  - r-tidyverse
  - r-data.table
  - r-here
  - r-renv
  # Bioconductor packages (optional to preseed)
  - r-biocmanager
  #- bioconductor-methylkit
